<?php
namespace axenox\GenAI\Factories;

use axenox\GenAI\AI\ResponseStatusMessages\AiResponseStatusMessage;
use axenox\GenAI\AI\ResponseStatusMessages\AiResponseStatusMessageWithAction;
use axenox\GenAI\Interfaces\AiResponseStatusMessageInterface;
use axenox\GenAI\Widgets\AIChat;
use exface\Core\CommonLogic\UxonObject;
use exface\Core\Exceptions\InvalidArgumentException;
use exface\Core\Factories\AbstractStaticFactory;
use exface\Core\Factories\ActionFactory;
use exface\Core\Interfaces\Actions\ActionInterface;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;
use exface\Core\Interfaces\WidgetInterface;

// Generated by GitHub Copilot
/**
 * Creates the standard AI response status message presets.
 */
class AiResponseStatusMessageFactory extends AbstractStaticFactory
{
	public const DATA_SHEET_WIDGET_PREVIEW = 'preview';

	public const DATA_SHEET_WIDGET_REVIEW = 'review';

	public const DATA_SHEET_WIDGET_CREATE = 'create';

	/**
	 * Creates an error status message.
	 */
	public static function createErrorMessage(string $text): AiResponseStatusMessageInterface
	{
		return new AiResponseStatusMessage('error', $text);
	}

	/**
	 * Creates a successful status message.
	 */
	public static function createOkMessage(string $text): AiResponseStatusMessageInterface
	{
		return new AiResponseStatusMessage('ok', $text);
	}

	/**
	 * Creates an informational status message.
	 */
	public static function createInfoMessage(string $text): AiResponseStatusMessageInterface
	{
		return new AiResponseStatusMessage('info', $text, 'blue');
	}

	/**
	 * Creates a warning status message.
	 */
	public static function createWarningMessage(string $text): AiResponseStatusMessageInterface
	{
		return new AiResponseStatusMessage('warning', $text, 'orange');
	}

	/**
	 * Creates a status message with a standard DataSheet dialog.
	 */
	public static function createDataSheetMessage(
		string $text,
		DataSheetInterface $sheet,
		WidgetInterface $contextWidget,
		string $widgetPreset = self::DATA_SHEET_WIDGET_PREVIEW
	): AiResponseStatusMessageInterface {
		$objectAlias = $sheet->getMetaObject()->getAliasWithNamespace();
		$dataSheetUxon = $sheet->exportUxonObject()->toArray();

		switch ($widgetPreset) {
			case self::DATA_SHEET_WIDGET_PREVIEW:
				$actionUxon = new UxonObject([
					'alias' => 'exface.Core.ShowDialog',
					'widget' => [
						'widget_type' => 'DataTable',
						'object_alias' => $objectAlias,
						'values_data_sheet' => $dataSheetUxon,
						'columns' => self::createDataSheetColumns($sheet),
						'lazy_loading' => false,
						'paginate' => false,
					],
				]);
				$buttonLabel = 'View data';
				$type = 'ok';
				break;
			case self::DATA_SHEET_WIDGET_REVIEW:
				$actionUxon = new UxonObject([
					'alias' => 'exface.Core.ShowDialog',
					'widget' => [
						'widget_type' => 'DataSpreadSheet',
						'object_alias' => $objectAlias,
						'values_data_sheet' => $dataSheetUxon,
						'columns' => self::createDataSheetColumns($sheet),
						'lazy_loading' => false,
						'paginate' => false,
						'editable' => true,
						'buttons' => [[
							'action_alias' => 'exface.Core.SaveData',
						]],
					],
				]);
				$buttonLabel = 'Review and save';
				$type = 'info';
				break;
			case self::DATA_SHEET_WIDGET_CREATE:
				$actionUxon = new UxonObject([
					'alias' => 'exface.Core.ShowObjectCreateDialog',
					'object_alias' => $objectAlias,
					'prefill_with_input_data' => false,
					'prefill_data_sheet' => $dataSheetUxon,
				]);
				$buttonLabel = 'Review and save';
				$type = 'info';
				break;
			default:
				throw new InvalidArgumentException('Unknown DataSheet status widget preset "' . $widgetPreset . '".');
		}

		$action = ActionFactory::createFromUxon(
			$contextWidget->getWorkbench(),
			$actionUxon,
			$contextWidget
		);

		return self::createShowWidgetMessage(
			$text,
			$action,
			$contextWidget,
			$buttonLabel,
			$type
		);
	}

	/**
	 * Creates a customizable status message that opens the widget of the supplied action.
	 */
	public static function createShowWidgetMessage(
		string $text,
		ActionInterface $action,
		WidgetInterface $contextWidget,
		string $buttonLabel = 'Details',
		string $type = 'info',
		?string $id = null
	): AiResponseStatusMessageInterface {
		$message = new AiResponseStatusMessageWithAction(
			$text,
			$action,
			$buttonLabel,
			$type,
			'',
			'ai',
			$id
		);

		if (! $contextWidget instanceof AIChat) {
			throw new InvalidArgumentException(
				'A show-widget status message can only register its action on an AIChat widget.'
			);
		}
		$contextWidget->registerActionWidget($action, $message->getId());

		return $message;
	}

	/**
	 * Builds widget columns from real DataSheet attribute aliases.
	 *
	 * @return array<int, array{attribute_alias: string}>
	 */
	private static function createDataSheetColumns(DataSheetInterface $sheet): array
	{
		$columns = [];
		foreach ($sheet->getColumns() as $column) {
			$attributeAlias = $column->getAttributeAlias();
			if ($attributeAlias !== null && $attributeAlias !== '') {
				$columns[] = ['attribute_alias' => $attributeAlias];
			}
		}

		return $columns;
	}
}