<?php
namespace axenox\GenAI\Factories;

use axenox\GenAI\AI\ResponseStatusMessages\AiResponseStatusMessage;
use axenox\GenAI\AI\ResponseStatusMessages\AiResponseStatusMessageWithAction;
use axenox\GenAI\Widgets\AIChat;
use exface\Core\Exceptions\InvalidArgumentException;
use exface\Core\Factories\AbstractStaticFactory;
use exface\Core\Interfaces\Actions\ActionInterface;
use exface\Core\Interfaces\WidgetInterface;

// Generated by GitHub Copilot
/**
 * Creates the standard AI response status message presets.
 */
class AiResponseStatusMessageFactory extends AbstractStaticFactory
{
	/**
	 * Creates an error status message.
	 */
	public static function createErrorMessage(string $text): AiResponseStatusMessage
	{
		return new AiResponseStatusMessage('error', $text);
	}

	/**
	 * Creates a successful status message.
	 */
	public static function createOkMessage(string $text): AiResponseStatusMessage
	{
		return new AiResponseStatusMessage('ok', $text);
	}

	/**
	 * Creates an informational status message.
	 */
	public static function createInfoMessage(string $text): AiResponseStatusMessage
	{
		return new AiResponseStatusMessage('info', $text, 'blue');
	}

	/**
	 * Creates a warning status message.
	 */
	public static function createWarningMessage(string $text): AiResponseStatusMessage
	{
		return new AiResponseStatusMessage('warning', $text, 'orange');
	}

	/**
	 * Creates a status message that opens the widget of the supplied action.
	 */
	public static function createShowWidgetMessage(
		string $text,
		ActionInterface $action,
		string $buttonLabel = 'Details',
		string $type = 'info',
		string $color = '#2563eb',
		string $role = 'ai',
		?WidgetInterface $contextWidget = null,
		?string $id = null
	): AiResponseStatusMessageWithAction {
		$message = new AiResponseStatusMessageWithAction(
			$text,
			$action,
			$buttonLabel,
			$type,
			$color,
			$role,
			$id
		);

		if ($contextWidget !== null && ! $contextWidget instanceof AIChat) {
			throw new InvalidArgumentException(
				'A show-widget status message can only register its action on an AIChat widget.'
			);
		}
		if ($contextWidget instanceof AIChat) {
			$contextWidget->registerActionWidget($action, $message->getId());
		}

		return $message;
	}
}