<?php
namespace axenox\GenAI\AI\UxonPresets;

use axenox\GenAI\Interfaces\AiStatusWidgetUxonPresetInterface;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;

// Generated by GitHub Copilot
/**
 * Shared helpers for DataSheet-based status-widget UXON presets.
 */
abstract class AbstractDataSheetUxonPreset implements AiStatusWidgetUxonPresetInterface
{
    /**
     * Builds widget columns from real DataSheet attribute aliases.
     *
     * @return array<int, array{attribute_alias: string}>
     */
    protected function createColumns(DataSheetInterface $sheet): array
    {
        $columns = [];
        foreach ($sheet->getColumns() as $column) {
            $attributeAlias = $column->getAttributeAlias();
            if ($attributeAlias !== null && $attributeAlias !== '') {
                $columns[] = ['attribute_alias' => $attributeAlias];
            }
        }

        return $columns;
    }
}
