<?php
namespace axenox\GenAI\AI\UxonPresets;

use exface\Core\CommonLogic\UxonObject;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;

// Generated by GitHub Copilot
/**
 * Builds a read-only DataTable dialog for imported data.
 */
class DataSheetPreviewUxonPreset extends AbstractDataSheetUxonPreset
{
    /**
     * Builds the preview-dialog action UXON.
     */
    public function createActionUxon(DataSheetInterface $sheet): UxonObject
    {
        return new UxonObject([
            'alias' => 'exface.Core.ShowDialog',
            'widget' => [
                'widget_type' => 'DataTable',
                'object_alias' => $sheet->getMetaObject()->getAliasWithNamespace(),
                'values_data_sheet' => $sheet->exportUxonObject()->toArray(),
                'columns' => $this->createColumns($sheet),
                'lazy_loading' => false,
                'paginate' => false,
            ],
        ]);
    }
}
