<?php
namespace axenox\GenAI\AI\UxonPresets;

use exface\Core\CommonLogic\UxonObject;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;

// Generated by GitHub Copilot
/**
 * Builds an editable DataSpreadSheet dialog for prepared import data.
 */
class DataSheetReviewUxonPreset extends AbstractDataSheetUxonPreset
{
    /**
     * Builds the editable review-and-save action UXON.
     */
    public function createActionUxon(DataSheetInterface $sheet): UxonObject
    {
        return new UxonObject([
            'alias' => 'exface.Core.ShowDialog',
            'widget' => [
                'widget_type' => 'DataSpreadSheet',
                'object_alias' => $sheet->getMetaObject()->getAliasWithNamespace(),
                'values_data_sheet' => $sheet->exportUxonObject()->toArray(),
                'columns' => $this->createColumns($sheet),
                'lazy_loading' => false,
                'paginate' => false,
                'editable' => true,
                'buttons' => [[
                    'action_alias' => 'exface.Core.SaveData',
                ]],
            ],
        ]);
    }
}
