<?php
namespace axenox\GenAI\AI\UxonPresets;

use exface\Core\CommonLogic\UxonObject;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;

// Generated by GitHub Copilot
/**
 * Builds an object-create dialog prefilled with prepared import data.
 */
class DataSheetCreateDialogUxonPreset extends AbstractDataSheetUxonPreset
{
    /**
     * Builds the prefilled object-create action UXON.
     */
    public function createActionUxon(DataSheetInterface $sheet): UxonObject
    {
        return new UxonObject([
            'alias' => 'exface.Core.ShowObjectCreateDialog',
            'object_alias' => $sheet->getMetaObject()->getAliasWithNamespace(),
            'prefill_with_input_data' => false,
            'prefill_data_sheet' => $sheet->exportUxonObject()->toArray(),
        ]);
    }
}
