<?php
namespace axenox\GenAI\Interfaces;

use exface\Core\CommonLogic\UxonObject;
use exface\Core\Interfaces\DataSheets\DataSheetInterface;

// Generated by GitHub Copilot
/**
 * Builds reusable action UXON for an AiStatusMessageWithWidget.
 */
interface AiStatusWidgetUxonPresetInterface
{
    /**
     * Builds action UXON for the supplied data sheet.
     */
    public function createActionUxon(DataSheetInterface $sheet): UxonObject;
}
