<?php
namespace axenox\GenAI\DataConnectors;

use axenox\GenAI\Common\DataQueries\OpenAiApiDataQuery;
use exface\Core\CommonLogic\AbstractDataConnector;
use exface\Core\CommonLogic\UxonObject;
use exface\Core\DataConnectors\Traits\IDoNotSupportTransactionsTrait;
use GuzzleHttp\Psr7\Response;
use Psr\Http\Message\ResponseInterface;

/**
 * Base connector for dry-run / mock handling.
 *
 * It simulates a tool-calling LLM cycle:
 * 1) return configured tool calls
 * 2) wait until GenericAssistant appends matching tool outputs
 * 3) return the final dry-run response
 */
abstract class AiDummyConnection extends AbstractDataConnector
{
    use IDoNotSupportTransactionsTrait;

    private bool $dryrun = false;

    private string $dryrunResponse = 'This is a pregenerated demo response because the AI connector has `dryrun:true`. This was not really generated by an LLM! See debug info below.';

    /**
     * Supported UXON formats:
     * {
     *   "tool_name": {"arguments": {"arg": "value"}, "id": "optional_call_id"}
     * }
     *
     * or
     *
     * [
     *   {"name": "tool_name", "arguments": {"arg": "value"}, "id": "optional_call_id"}
     * ]
     *
     * @var array<int|string, mixed>
     */
    private array $dryrunToolCalls = [];

    protected function isDryrun() : bool
    {
        return $this->dryrun;
    }

    /**
     * Set to TRUE to return pregenerated responses instead of really querying the LLM.
     *
     * @uxon-property dryrun
     * @uxon-type boolean
     * @uxon-default false
     */
    protected function setDryrun(bool $value) : AiDummyConnection
    {
        $this->dryrun = $value;
        return $this;
    }

    protected function getDryrunResponseText() : string
    {
        return $this->dryrunResponse;
    }

    /**
     * Final assistant message returned after all configured dry-run tool calls are answered.
     *
     * @uxon-property dryrunResponse
     * @uxon-type string
     */
    protected function setDryrunResponse(string $value) : AiDummyConnection
    {
        $this->dryrunResponse = $value;
        return $this;
    }

    /**
     * Configures dry-run tool calls emitted by the connector.
     *
     * @uxon-property dryrun_tool_calls
     * @uxon-type object
     * @uxon-template {"my_tool":{"arguments":{"example":"value"}}}
     */
    protected function setDryrunToolCalls($value) : AiDummyConnection
    {
        $this->dryrunToolCalls = $value instanceof UxonObject ? $value->toArray() : (array) $value;
        return $this;
    }

    protected function getDryrunResponse(OpenAiApiDataQuery $query, array $requestJson) : ResponseInterface
    {
        $plannedCalls = $this->buildDryrunToolPlan($query);
        $answeredCallIds = $this->collectAnsweredCallIds($query);
        $pendingCalls = array_values(array_filter(
            $plannedCalls,
            static fn(array $call) : bool => in_array($call['id'], $answeredCallIds, true) === false
        ));

        if (! empty($pendingCalls)) {
            return $this->buildDryrunToolCallResponse($requestJson, $pendingCalls, $plannedCalls, $answeredCallIds);
        }

        return $this->buildDryrunFinalResponse($requestJson, $plannedCalls, $answeredCallIds);
    }

    /**
     * @return array<int, array{id:string,name:string,arguments:array|object}>
     */
    protected function buildDryrunToolPlan(OpenAiApiDataQuery $query) : array
    {
        $configured = $this->dryrunToolCalls;
        $calls = [];

        if (empty($configured)) {
            foreach (array_values($query->getTools()) as $idx => $tool) {
                $calls[] = [
                    'id' => 'call_dryrun_' . ($idx + 1),
                    'name' => $tool->getName(),
                    'arguments' => new \stdClass(),
                ];
            }
            return $calls;
        }

        if ($this->isAssocArray($configured)) {
            $index = 0;
            foreach ($configured as $toolName => $definition) {
                $index++;
                $calls[] = $this->normalizeDryrunToolCall((string) $toolName, $definition, $index);
            }
            return $calls;
        }

        foreach (array_values($configured) as $idx => $definition) {
            if (! is_array($definition)) {
                continue;
            }

            $toolName = (string) ($definition['name'] ?? $definition['tool'] ?? $definition['tool_name'] ?? '');
            if ($toolName === '') {
                continue;
            }

            $calls[] = $this->normalizeDryrunToolCall($toolName, $definition, $idx + 1);
        }

        return $calls;
    }

    /**
     * @param mixed $definition
     * @return array{id:string,name:string,arguments:array|object}
     */
    protected function normalizeDryrunToolCall(string $toolName, $definition, int $index) : array
    {
        $arguments = [];
        $callId = 'call_dryrun_' . $index;

        if (is_array($definition)) {
            $arguments = $definition['arguments'] ?? $definition['args'] ?? [];
            $callId = (string) ($definition['id'] ?? $callId);
        }

        if (! is_array($arguments)) {
            $arguments = [];
        }

        return [
            'id' => $callId,
            'name' => $toolName,
            'arguments' => $arguments,
        ];
    }

    /**
     * @return string[]
     */
    protected function collectAnsweredCallIds(OpenAiApiDataQuery $query) : array
    {
        $answered = [];

        foreach ($query->getMessages(true) as $message) {
            if (($message['role'] ?? null) !== 'tool') {
                continue;
            }

            $callId = $message['tool_call_id'] ?? $message['call_id'] ?? null;
            if (is_string($callId) && $callId !== '') {
                $answered[] = $callId;
            }
        }

        return array_values(array_unique($answered));
    }

    /**
     * @param array<int, array{id:string,name:string,arguments:array|object}> $pendingCalls
     * @param array<int, array{id:string,name:string,arguments:array|object}> $plannedCalls
     * @param string[] $answeredCallIds
     */
    protected function buildDryrunToolCallResponse(array $requestJson, array $pendingCalls, array $plannedCalls, array $answeredCallIds) : ResponseInterface
    {
        $debug = [
            'request' => $requestJson,
            'dryrun_mode' => 'tool_calls',
            'planned_calls' => $plannedCalls,
            'answered_call_ids' => $answeredCallIds,
        ];

        if ($this->getApiType() === 'responses') {
            $output = [];
            foreach ($pendingCalls as $call) {
                $output[] = [
                    'type' => 'function_call',
                    'call_id' => $call['id'],
                    'name' => $call['name'],
                    'arguments' => json_encode($call['arguments'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                ];
            }

            return new Response(200, [], json_encode([
                'id' => 'resp_dryrun_toolcalls_001',
                'object' => 'response',
                'created_at' => time(),
                'status' => 'completed',
                'model' => $this->getModelName(),
                'output' => $output,
                'parallel_tool_calls' => true,
                'tool_choice' => 'auto',
                'usage' => [
                    'input_tokens' => 0,
                    'output_tokens' => 0,
                    'total_tokens' => 0,
                ],
                'debug' => $debug,
            ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
        }

        $toolCalls = [];
        foreach ($pendingCalls as $call) {
            $toolCalls[] = [
                'id' => $call['id'],
                'type' => 'function',
                'function' => [
                    'name' => $call['name'],
                    'arguments' => json_encode($call['arguments'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES),
                ],
            ];
        }

        return new Response(200, [], json_encode([
            'id' => 'chatcmpl-dryrun-toolcalls-001',
            'object' => 'chat.completion',
            'created' => time(),
            'model' => $this->getModelName(),
            'choices' => [
                [
                    'index' => 0,
                    'finish_reason' => 'tool_calls',
                    'message' => [
                        'role' => 'assistant',
                        'content' => '',
                        'tool_calls' => $toolCalls,
                    ],
                ],
            ],
            'usage' => [
                'prompt_tokens' => 0,
                'completion_tokens' => 0,
                'total_tokens' => 0,
            ],
            'debug' => $debug,
        ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    }

    /**
     * @param array<int, array{id:string,name:string,arguments:array|object}> $plannedCalls
     * @param string[] $answeredCallIds
     */
    protected function buildDryrunFinalResponse(array $requestJson, array $plannedCalls, array $answeredCallIds) : ResponseInterface
    {
        $debug = [
            'request' => $requestJson,
            'dryrun_mode' => 'final_response',
            'planned_calls' => $plannedCalls,
            'answered_call_ids' => $answeredCallIds,
        ];

        if ($this->getApiType() === 'responses') {
            return new Response(200, [], json_encode([
                'id' => 'resp_dryrun_final_001',
                'object' => 'response',
                'created_at' => time(),
                'status' => 'completed',
                'model' => $this->getModelName(),
                'output' => [
                    [
                        'type' => 'message',
                        'id' => 'msg_dryrun_001',
                        'status' => 'completed',
                        'role' => 'assistant',
                        'content' => [
                            [
                                'type' => 'output_text',
                                'text' => $this->getDryrunResponseText(),
                                'annotations' => [],
                            ],
                        ],
                    ],
                ],
                'parallel_tool_calls' => true,
                'tool_choice' => 'auto',
                'usage' => [
                    'input_tokens' => 0,
                    'output_tokens' => 0,
                    'total_tokens' => 0,
                ],
                'debug' => $debug,
            ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
        }

        return new Response(200, [], json_encode([
            'id' => 'chatcmpl-dryrun-final-001',
            'object' => 'chat.completion',
            'created' => time(),
            'model' => $this->getModelName(),
            'choices' => [
                [
                    'index' => 0,
                    'finish_reason' => 'stop',
                    'message' => [
                        'role' => 'assistant',
                        'content' => $this->getDryrunResponseText(),
                    ],
                ],
            ],
            'usage' => [
                'prompt_tokens' => 0,
                'completion_tokens' => 0,
                'total_tokens' => 0,
            ],
            'debug' => $debug,
        ], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
    }

    protected function isAssocArray(array $value) : bool
    {
        return array_keys($value) !== range(0, count($value) - 1);
    }

    abstract protected function getApiType() : string;

    abstract public function getModelName() : string;
}
